### PR TITLE
Attempt to fixed Bug #73539

### PR DESCRIPTION
**Pull request by rossaffandy**
Please view https://bugs.php.net/bug.php?id=73539 for details

### CODE REVIEW

**Comment by tomassrnka** [comment]
Hi, thanks, I created pull request for your patch to fix formatting + I will test the patch, then we can merge it.

**Comment by norrs** [comment]
Curious, have you tested and verified this in any kind of production environment @tomassrnka ? Seems like this PR has been forgotten. cc @rossaffandy

**Comment by tomassrnka** [comment]
Ou thanks, yes. It seems to be working fine. I will give it an extensive test next week, but i think it should be OK.

**Comment by norrs** [comment]
@tomassrnka : It could be that https://github.com/php/php-src/commit/2d19c92fc2f14aa97db9094eaa0b67d1c3b12409 does fix this in upstream? Sadly someone with more C knowledge then me should confirm it.

**Pull request merged**
