### PR TITLE
readd this for php < 7.2

### PR DESCRIPTION
**Pull request by Jan-E**
Remaining part of https://github.com/websupport-sk/pecl-memcache/pull/30

### CODE REVIEW

**Comment by Jan-E** [comment]
@tomassrnka Any reason why you did not merge this one into the new release? It really is needed for PHP 7.1, in particular on Windows. @remicollet Can you confirm this?

**Comment by remicollet** [comment]
Yes, this is need everywhere.
Don't understand, why this PR, as this is part of PR #30

**Comment by Jan-E** [comment]
https://github.com/websupport-sk/pecl-memcache/pull/30 was superseded by other commits and has conflicts now. It canot be merged anymore.

**Comment by remicollet** [comment]
Indeed, so +41 for this change.

**Comment by tomassrnka** [comment]
Thx merged

**Pull request merged**
